### ISSUE TITLE
No longer works on 4.13

### ISSUE THREAD

**Issue by Cheetohs** [Sadret/openrct2-price-manager#10] opened 2024-09-03 23:25 UTC
I continually get a "invalid parameters" tick with each attempted price update. Tried a clean install of the plugin but it didn't help.

**Comment by Sadret** [comment] 2024-09-04 08:47
Duplicate of #8 - next time, please check the open issues before creating a new one ;)

For now, limit your ticket prices to 20 €/$.

**Closed by Sadret** 2024-09-04 08:47 UTC

**Comment by Cheetohs** [comment] 2024-09-04 12:04
Fully unnecessary to add a winky face if you want to pretend to be funny. That comes off as rude.
